### ISSUE TITLE
GeoNode Cloud Layer Display Issue: Requires Authentication on GeoServer

### ISSUE THREAD

**Issue by dgquail** [Kan-T-IT/geonode-cloud#1]
**#8165**
Layers in GeoNode Cloud do not display correctly unless logged into GeoServer, affecting both public and private layers.

**Steps to Reproduce the Issue:**

1. Log into GeoNode with administrator credentials.
2. Select an uploaded layer or upload a new one.
3. Verify that the layer does not load correctly.
4. Log into GeoServer.
5. Return to GeoNode and attempt to view the same layer that did not load previously.
6. Log out and re-enter GeoNode without authenticating.
7. Select a layer marked as public.
8. Repeat the previous steps to check if the public layer loads.

**Expected Result:**

- Layers should be viewable in GeoNode without needing to log into GeoServer.
- Public layers should be viewable directly in GeoNode without needing to authenticate in either GeoNode or GeoServer.

**Actual Result:**

It is necessary to log into GeoServer to view layers in GeoNode, regardless of whether they are public or private.

**Comment by VladiGuive** [comment]
Once you added the geonode-oauth2 identification filter you have to select it on all the avaiable filter chains, abobe of the shared auth option

Also you will need to add two new filter chains that use this auth:

Name: sld service
ANT list: /rest/sldservice/**
And select the: basic, geonode-oauth2 and shared filters (in that order) 

Name: gwc service
ANT list: /gwc/service/**
And select the: basic, geonode-oauth2 and shared filters (in that order) 

Then you have to move this filters avobe of their matching parents urls

Use this ordes as an example

```
# other filters...
/rest/sldservice/**  # Our new filter
/rest/**             # A default filter
/gwc/service/**      # Our new filter
/gwc/**              # A default filter
/**                  # A default filter
# ...other filters
```
