### ISSUE TITLE
Error Loading TIFF and GeoPackage Layers

### ISSUE THREAD

**Issue by dgquail** [Kan-T-IT/geonode-cloud#2]
**#8175**
**Steps to Reproduce the Issue:**

1. Enter to the geonode cloud
2. Select "Add resource."
3. Select "Upload dataset."
4. Upload a TIFF or GeoPackage layer.

**Expected Results:**
All file types displayed when uploading layers should upload correctly.
![image](https://github.com/user-attachments/assets/9d3e5553-345f-4744-8a7e-df3007726964)

**Actual Results:**
An error occurs when uploading TIFF or GeoPackage layers
![image](https://github.com/user-attachments/assets/d99e9535-b936-492f-b5e7-76b6054a7c5b)

**Comment by ramiro1993** [comment]
the problem was corrected
