### ISSUE TITLE
Error uploading heavy layers

### ISSUE THREAD

**Issue by dgquail** [Kan-T-IT/geonode-cloud#5]
**#8163**
**When Attempting to Upload Large Layers in Geonode Cloud, an Error Occurs Suggesting to Check the File's "Validity," Despite These Files Having Been Successfully Tested and Uploaded in Other GeoNode Instances**

**Steps to Reproduce the Issue:**

1. Log into Geonode Cloud
2. Navigate to the "Add Resource" section.
3. Select "Upload Dataset."
4. Attempt to upload a large layer

**Expected Result:**

The layers should upload correctly without any issues.

**Actual Result:**

When attempting to upload large layers, an error occurs indicating that the file's "validity" needs to be checked. (see image)
![image](https://github.com/user-attachments/assets/57b91b7c-bcbb-4c54-b72a-0f0b9ddcf5c0)

**Comment by ramiro1993** [comment]
now already allows for the loading of large layers.
