### ISSUE TITLE
Testing Deploy in EKS

### ISSUE THREAD

**Issue by anthieni** [Kan-T-IT/geonode-cloud#6]
Generate testing to deployment in EKS Cluster

**Comment by ramiro1993** [comment]
se realizaron avances sobre los cambios.
el cluster se encuentra levantado y se adaptaron los yaml a aplicar.
Se continua de igual manera revisando los mismos.

Dejo una serie de pasos y pendientes para aplicar el despliege

Preparar la Aplicación para el despliegue

    Adaptar URLs para que apunten al dominio que se va a crear.
    Crear el dominio: Registra el dominio en Route 53 u otro registrador de dominios.
    Crear el certificado ACM: En AWS Certificate Manager (ACM), crea el certificado para el dominio.

Configurar el AWS Load Balancer Controller

    Revisar los IAM roles necesarios para el controlador.

Configurar el DNS

    Apuntar dominio a la dirección IP del ALB.
    Configurar HTTPS.

Crear la StorageClass gp3

    Definir la StorageClass gp3 si no existe en el clúster.

Instalar el AWS Load Balancer Controller

    Utiliza Helm para instalar el controlador.

Desplegar la Aplicación

    Aplicar los YAMLs.

**Comment by ramiro1993** [comment]
Progress has been made on the changes. The cluster is up, and the YAMLs to be applied have been adapted. We continue reviewing them as well.

Below is a list of steps and pending tasks for the deployment:

Prepare the Application for Deployment:

    Adapt URLs to point to the domain that will be created.
    Create the domain: Register the domain in Route 53 or another domain registrar.
    Create the ACM certificate: In AWS Certificate Manager (ACM), create the certificate for the domain.

Configure the AWS Load Balancer Controller:

    Review the necessary IAM roles for the controller.

Configure the DNS:

    Point the domain to the ALB's IP address.
    Set up HTTPS.

Create the StorageClass gp3:

    Define the gp3 StorageClass if it doesn't exist in the cluster.

Install the AWS Load Balancer Controller:

    Use Helm to install the controller.

Deploy the Application:

    Apply the YAML files.

**Comment by ramiro1993** [comment]
successful tests
